[package]
name = "zksim-circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
zksim-core = { path = "../core" }
ark-ff = "0.4"
ark-std = "0.4"
ark-bn254 = "0.4"
ark-r1cs-std = "0.4"
ark-relations = "0.4"
ark-crypto-primitives = { version = "0.4", features = ["r1cs", "sponge"] }
